- hosts: servers
  become_user: root
  remote_user: cpd
  become: yes
  vars:
    # ip link show
    physical_interfaces:
      - ens1f0
      - ens1f1
      - ens1f2
      - ens1f3
      - eno8303
      - eno8403
  roles:
    - { role: libvirtd }
