- name: put config template
  vars:
    hosts:
     - "dcnetvm_k8s1"
     - "dcnetvm5"
     - "dcnetvm_admins"
  template:
    src: config.yml.j2
    dest: $HOME/.config/virt-backup/config.yml
    mode: 0755