- name: copy .ssh/terraformlibvirt private key
  copy:
    src: ~/.ssh/terraformlibvirt
    dest: "/root/.ssh/terraformlibvirt"
    owner: "root"
    group: "root"
    mode: 0600

- name: run ansible k8s-playbook
  shell: ansible-playbook k8s-playbook.yml -v
  args:
    chdir: /src/ansible-kubeadm

- name: kubeconfig
  block:
    - name: create ~/.kube directory
      file:
        state: directory
        name: $HOME/.kube
    - name: copy
      shell: scp -i ~/.ssh/terraformlibvirt debian@192.168.124.10:/home/debian/.kube/config ~/.kube/config
      args:
        chdir: /src/ansible-kubeadm
