- name: download kubectl
  vars:
    kubectl_version: v1.28.1
  get_url:
    url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/
    owner: "{{ ansible_ssh_user }}"
    mode: 0770

- name: download k9s
  vars:
    k9s_version: v0.31.9
  unarchive:
    src: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
    dest: /usr/local/bin/
    remote_src: yes
    owner: "{{ ansible_ssh_user }}"
    group: root
    mode: "0770"

- name: terraform cli
  block:
    - name: download
      vars:
        terraform_version: 1.7.4
      get_url:
        url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: /tmp/terraform.zip
        owner: "{{ ansible_ssh_user }}"
        mode: 0770
    - name: unzip
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes
        owner: "{{ ansible_ssh_user }}"
        group: root
        mode: "0770"

- name: vault cli
  block:
    - name: download
      vars:
        vault_version: 1.15.6
      get_url:
        url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
        dest: /tmp/vault.zip
        owner: "{{ ansible_ssh_user }}"
        mode: 0770
    - name: unzip
      unarchive:
        src: /tmp/vault.zip
        dest: /usr/local/bin/
        remote_src: yes
        owner: "{{ ansible_ssh_user }}"
        group: root
        mode: "0770"

- name: download argocd
  vars:
    argocd_version: v2.10.3
  get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/argocd-linux-amd64"
    dest: /usr/local/bin/argocd
    owner: "{{ ansible_ssh_user }}"
    mode: 0770
# - name: download istio
#   vars:
#     istioctl_version: 1.21.0
#   unarchive:
#     src: "https://github.com/istio/istio/releases/download/{{ istioctl_version }}/istioctl-{{ istioctl_version }}-linux-amd64.tar.gz"
#     dest: /usr/local/bin/
#     remote_src: yes
#     owner: "{{ ansible_ssh_user }}"
#     group: root
#     mode: "0770"
