- name: download kubectl
  vars:
    kubectl_version: v1.28.1
  get_url:
    url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/
    owner: "{{ ansible_ssh_user }}"
    mode: 0770

- name: download k9s
  vars:
    k9s_version: v0.31.9
  unarchive:
    src: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
    dest: /usr/local/bin/
    remote_src: yes
    owner: "{{ ansible_ssh_user }}"
    group: root
    mode: "0770"

- name: terraform cli
  block:
    - name: download
      vars:
        terraform_version: 1.7.4
      get_url:
        url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: /tmp/terraform.zip
        owner: "{{ ansible_ssh_user }}"
        mode: 0770
    - name: unzip
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes
        owner: "{{ ansible_ssh_user }}"
        group: root
        mode: "0770"
